services:
  _defaults:
    autowire: true
    autoconfigure: true
    public: false
    bind:
      $allowedIps: '%contao_iplogin.allowed_ips%'

  InspiredMinds\ContaoIpLoginBundle\:
    resource: ../../
    exclude: ../../{ContaoManager,DependencyInjection,Resources}
